package com.lynu.yzshopping.mybatis.persistence;

import com.lynu.yzshopping.mybatis.entity.Manager;
import com.lynu.yzshopping.mybatis.entity.User;

import java.util.List;
import java.util.Map;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    Manager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    int updateByPrimaryKey(Manager record);


    /*
    * 根据条件进行查询
    * */
    List<Manager> selectByConditionMap(Map<String,Object> map);
}