package com.lynu.yzshopping.mybatis.persistence;

import com.lynu.yzshopping.mybatis.entity.ReceiveAddress;

import java.lang.reflect.MalformedParameterizedTypeException;
import java.util.List;
import java.util.Map;

public interface ReceiveAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_address
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_address
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    int insert(ReceiveAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_address
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    int insertSelective(ReceiveAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_address
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    ReceiveAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_address
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    int updateByPrimaryKeySelective(ReceiveAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_address
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    int updateByPrimaryKey(ReceiveAddress record);

    List<ReceiveAddress> selectByConditionMap(Map<String,Object> map);
}