package com.lynu.yzshopping.mybatis.persistence;

import com.lynu.yzshopping.mybatis.entity.Record;

import java.util.List;
import java.util.Map;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    Record selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    int updateByPrimaryKey(Record record);

    List<Record> selectByConditionMap(Map<String, Object> map) ;

     List<String> loadDomainBySearchKey(String searchKey);
}