package com.lynu.yzshopping.mybatis.persistence;

import com.lynu.yzshopping.mybatis.entity.Score;

import java.util.List;
import java.util.Map;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Tue Apr 02 13:24:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Tue Apr 02 13:24:16 CST 2019
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Tue Apr 02 13:24:16 CST 2019
     */
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Tue Apr 02 13:24:16 CST 2019
     */
    Score selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Tue Apr 02 13:24:16 CST 2019
     */
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Tue Apr 02 13:24:16 CST 2019
     */
    int updateByPrimaryKey(Score record);

    public List<Score> selectByConditionMap(Map<String, Object> map) ;
}