package com.lynu.yzshopping.mybatis.persistence;

import com.lynu.yzshopping.mybatis.entity.Score;
import com.lynu.yzshopping.mybatis.entity.UserGoodMapping;

import java.util.List;
import java.util.Map;

public interface UserGoodMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_good_mapping
     *
     * @mbggenerated Tue Apr 16 16:12:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_good_mapping
     *
     * @mbggenerated Tue Apr 16 16:12:42 CST 2019
     */
    int insert(UserGoodMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_good_mapping
     *
     * @mbggenerated Tue Apr 16 16:12:42 CST 2019
     */
    int insertSelective(UserGoodMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_good_mapping
     *
     * @mbggenerated Tue Apr 16 16:12:42 CST 2019
     */
    UserGoodMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_good_mapping
     *
     * @mbggenerated Tue Apr 16 16:12:42 CST 2019
     */
    int updateByPrimaryKeySelective(UserGoodMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_good_mapping
     *
     * @mbggenerated Tue Apr 16 16:12:42 CST 2019
     */
    int updateByPrimaryKey(UserGoodMapping record);

    List<UserGoodMapping> selectByConditionMap(Map<String, Object> map) ;
}