package com.lynu.yzshopping.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class Manager implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.id
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.account
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.username
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.role_id
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.create_time
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.update_time
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.id
     *
     * @return the value of manager.id
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.id
     *
     * @param id the value for manager.id
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.account
     *
     * @return the value of manager.account
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.account
     *
     * @param account the value for manager.account
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.username
     *
     * @return the value of manager.username
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.username
     *
     * @param username the value for manager.username
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.role_id
     *
     * @return the value of manager.role_id
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.role_id
     *
     * @param roleId the value for manager.role_id
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.create_time
     *
     * @return the value of manager.create_time
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.create_time
     *
     * @param createTime the value for manager.create_time
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.update_time
     *
     * @return the value of manager.update_time
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.update_time
     *
     * @param updateTime the value for manager.update_time
     *
     * @mbggenerated Fri Apr 12 15:16:27 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}