package com.lynu.yzshopping.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class ReceiveAddress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.id
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.user_id
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.receive_name
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private String receiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.receive_phone
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private String receivePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.province
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.city
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.county
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.address_detail
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private String addressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.create_time
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.update_time
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.id
     *
     * @return the value of receive_address.id
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.id
     *
     * @param id the value for receive_address.id
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.user_id
     *
     * @return the value of receive_address.user_id
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.user_id
     *
     * @param userId the value for receive_address.user_id
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.receive_name
     *
     * @return the value of receive_address.receive_name
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.receive_name
     *
     * @param receiveName the value for receive_address.receive_name
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.receive_phone
     *
     * @return the value of receive_address.receive_phone
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public String getReceivePhone() {
        return receivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.receive_phone
     *
     * @param receivePhone the value for receive_address.receive_phone
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setReceivePhone(String receivePhone) {
        this.receivePhone = receivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.province
     *
     * @return the value of receive_address.province
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.province
     *
     * @param province the value for receive_address.province
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.city
     *
     * @return the value of receive_address.city
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.city
     *
     * @param city the value for receive_address.city
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.county
     *
     * @return the value of receive_address.county
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.county
     *
     * @param county the value for receive_address.county
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.address_detail
     *
     * @return the value of receive_address.address_detail
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.address_detail
     *
     * @param addressDetail the value for receive_address.address_detail
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.create_time
     *
     * @return the value of receive_address.create_time
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.create_time
     *
     * @param createTime the value for receive_address.create_time
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.update_time
     *
     * @return the value of receive_address.update_time
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.update_time
     *
     * @param updateTime the value for receive_address.update_time
     *
     * @mbggenerated Wed Apr 03 17:48:51 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}