package com.lynu.yzshopping.mybatis.entity;

import java.util.Date;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.search_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String searchKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.title
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.service_url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String serviceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.p_url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String pUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.img_url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.price
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.domain
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.domainCH
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String domainch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.brand
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.service
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.comnum
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private Integer comnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.h_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String hKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.row_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String rowKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.group_row_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private String groupRowKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.create_time
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.search_key
     *
     * @return the value of record.search_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getSearchKey() {
        return searchKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.search_key
     *
     * @param searchKey the value for record.search_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setSearchKey(String searchKey) {
        this.searchKey = searchKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.title
     *
     * @return the value of record.title
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.title
     *
     * @param title the value for record.title
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.service_url
     *
     * @return the value of record.service_url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getServiceUrl() {
        return serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.service_url
     *
     * @param serviceUrl the value for record.service_url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.p_url
     *
     * @return the value of record.p_url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getpUrl() {
        return pUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.p_url
     *
     * @param pUrl the value for record.p_url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setpUrl(String pUrl) {
        this.pUrl = pUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.url
     *
     * @return the value of record.url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.url
     *
     * @param url the value for record.url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.img_url
     *
     * @return the value of record.img_url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.img_url
     *
     * @param imgUrl the value for record.img_url
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.price
     *
     * @return the value of record.price
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.price
     *
     * @param price the value for record.price
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.domain
     *
     * @return the value of record.domain
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.domain
     *
     * @param domain the value for record.domain
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.domainCH
     *
     * @return the value of record.domainCH
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getDomainch() {
        return domainch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.domainCH
     *
     * @param domainch the value for record.domainCH
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setDomainch(String domainch) {
        this.domainch = domainch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.brand
     *
     * @return the value of record.brand
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.brand
     *
     * @param brand the value for record.brand
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.service
     *
     * @return the value of record.service
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.service
     *
     * @param service the value for record.service
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setService(String service) {
        this.service = service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.comnum
     *
     * @return the value of record.comnum
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public Integer getComnum() {
        return comnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.comnum
     *
     * @param comnum the value for record.comnum
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setComnum(Integer comnum) {
        this.comnum = comnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.h_key
     *
     * @return the value of record.h_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String gethKey() {
        return hKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.h_key
     *
     * @param hKey the value for record.h_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void sethKey(String hKey) {
        this.hKey = hKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.row_key
     *
     * @return the value of record.row_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getRowKey() {
        return rowKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.row_key
     *
     * @param rowKey the value for record.row_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setRowKey(String rowKey) {
        this.rowKey = rowKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.group_row_key
     *
     * @return the value of record.group_row_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public String getGroupRowKey() {
        return groupRowKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.group_row_key
     *
     * @param groupRowKey the value for record.group_row_key
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setGroupRowKey(String groupRowKey) {
        this.groupRowKey = groupRowKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.create_time
     *
     * @return the value of record.create_time
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.create_time
     *
     * @param createTime the value for record.create_time
     *
     * @mbggenerated Mon Apr 22 18:58:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}