package com.lynu.yzshopping.mybatis.entity;

public class ScoreShop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_shop.id
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_shop.g_title
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    private String gTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_shop.g_image_url
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    private String gImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_shop.g_price
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    private String gPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_shop.g_number
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    private String gNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_shop.g_delete
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    private String gDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_shop.id
     *
     * @return the value of score_shop.id
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_shop.id
     *
     * @param id the value for score_shop.id
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_shop.g_title
     *
     * @return the value of score_shop.g_title
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public String getgTitle() {
        return gTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_shop.g_title
     *
     * @param gTitle the value for score_shop.g_title
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public void setgTitle(String gTitle) {
        this.gTitle = gTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_shop.g_image_url
     *
     * @return the value of score_shop.g_image_url
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public String getgImageUrl() {
        return gImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_shop.g_image_url
     *
     * @param gImageUrl the value for score_shop.g_image_url
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public void setgImageUrl(String gImageUrl) {
        this.gImageUrl = gImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_shop.g_price
     *
     * @return the value of score_shop.g_price
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public String getgPrice() {
        return gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_shop.g_price
     *
     * @param gPrice the value for score_shop.g_price
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public void setgPrice(String gPrice) {
        this.gPrice = gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_shop.g_number
     *
     * @return the value of score_shop.g_number
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public String getgNumber() {
        return gNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_shop.g_number
     *
     * @param gNumber the value for score_shop.g_number
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public void setgNumber(String gNumber) {
        this.gNumber = gNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_shop.g_delete
     *
     * @return the value of score_shop.g_delete
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public String getgDelete() {
        return gDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_shop.g_delete
     *
     * @param gDelete the value for score_shop.g_delete
     *
     * @mbggenerated Mon Apr 01 11:16:33 CST 2019
     */
    public void setgDelete(String gDelete) {
        this.gDelete = gDelete;
    }
}