server:
     port: 9090
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/yzshopping?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
        encoding:
            force: true
            charset: utf-8
            enabled: true
    thymeleaf:
        cache: false
    devtools:
        restart:
            enabled: true
mybatis:
#对应实体类的路径 和 mapper映射文件xml的路径
    typeAliasesPackage: com.eiis.mybatis.entity
    mapperLocations: classpath:mybatisMapper/*.xml
    configLocation:  classpath:mybatisConfig/mybatis-configuration.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#本地测试用看日志
logging:
  #file: god.log
  #path: /Users/wujiaqi/Desktop
  #level: debug
  config: classpath:logbackConfig/logback-eiisyspn-dev.xml
